version: '3.5'
services:

  # The application (PHP)
  app:
    # TODO

  # The web server (NGINX)
  web:
    # TODO


  # The db (MYSQL)
  db:
    # TODO


  # The cache (redis)
  redis:
    # TODO


  # Handle emails (mailhog)
  emails:
    # TODO


#Docker Networks
networks:
  myappnetwork:
    driver: bridge
